config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders
    resources :materials
  end

  resources :products
  get '/my_products', to: 'products#my_index'
  get '/my_products/:id', to: 'products#my_show'
  get 'top/index'

  resources :designs
  get '/my_designs', to: 'designs#my_index'

  resources :orders do
    collection do
      post :confirm
    end
  end
  get 'users/new'
  resources :users

  get 'password_resets/new'
  get 'password_resets/edit'

  root 'top#index'

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :account_activations, only: [:edit]

#  get 'static_pages/help'
#  get 'static_pages/about'
#  get 'static_pages/contact'

  #root 'application#hello'

  get 'login/index'
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/material.rb
# == Schema Information
#
# Table name: materials
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  description     :text(65535)
#  enable_cut      :boolean          default(FALSE), not null
#  print_type      :integer          not null
#  price           :integer
#  provide_status  :integer          not null
#  active          :integer
#  created_user_id :integer
#  updated_user_id :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Material < ApplicationRecord
  # = Module & Configure
  enum print_type: {
    unavailable: 0,
    single_color: 10,
    tone_color: 20
  }

  enum provide_status: {
    discontinued: 0,
    sale: 10,
    backorder: 20,
  }

  # = Association
  has_many :designs
  has_many :products

  # = Callback


  # = Instance method

end

app/controllers/admin/materials_controller.rb
class Admin::MaterialsController < ApplicationController
  skip_before_action :require_login
  before_action :set_material, only: [:show, :edit, :update, :destroy]

  # GET /materials
  # GET /materials.json
  def index
    @materials = Material.all
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit
    @material = Material.find(params[:id])
  end

  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(material_params)

    if @material.save
      redirect_to action: :index
    else
      format.html { render :new }
    end
  end

  # PATCH/PUT /materials/1
  # PATCH/PUT /materials/1.json
  def update
    if @material.update(material_params)
      redirect_to action: :index
    else
      format.html { render :edit }
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    @material.destroy
    respond_to do |format|
      format.html { redirect_to materials_url, notice: 'Material was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_params
      params.require(:material).permit(:name, :description, :enable_cut, :print_type, :price, :provide_status)
    end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  skip_before_action :require_login
  before_action :set_material, only: [:show, :edit, :update, :destroy]

  # GET /materials
  # GET /materials.json
  def index
    @materials = Material.all
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(material_params)

    respond_to do |format|
      if @material.save
        format.html { redirect_to @material, notice: 'Material was successfully created.' }
        format.json { render :show, status: :created, location: @material }
      else
        format.html { render :new }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1
  # PATCH/PUT /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to @material, notice: 'Material was successfully updated.' }
        format.json { render :show, status: :ok, location: @material }
      else
        format.html { render :edit }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    @material.destroy
    respond_to do |format|
      format.html { redirect_to materials_url, notice: 'Material was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_params
      params.require(:material).permit(:content_type, :content_value, :status, :internal_comment, :external_comment, :created_user_id, :updated_user_id, :active)
    end
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/admin/materials/_form.html.erb
<%= form_for material, url: path_to_submit do |f| %>
  <% if material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
      <% material.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table class="table" width="90%">
    <tbody>
      <tr>
        <td><%= f.label :name %></td>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <td><%= f.label :description %></td>
        <td><%= f.text_field :description %></td>
      </tr>
      <tr>
        <td><%= f.label :enable_cut %></td>
        <td><%= f.check_box :enable_cut %></td>
      </tr>
      <tr>
        <td><%= f.label :print_type %></td>
        <td>
          <%= f.select :print_type, Material.print_types_i18n.keys.map { |k| [Material.print_types_i18n[k], k] } %>
        </td>
      </tr>
      <tr>
        <td><%= f.label :price %></td>
        <td><%= f.number_field :price %></td>
      </tr>
      <tr>
        <td><%= f.label :provide_status %></td>
        <td>
          <%= f.select :provide_status, Material.provide_statuses_i18n.keys.map { |k| [Material.provide_statuses_i18n[k], k] } %>
        </td>
      </tr>
    </tbody>
  <table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/materials/edit.html.erb
<h1>Editing Material</h1>

<%= render partial: 'form', locals: { material: @material, path_to_submit: admin_material_path } %>

<%= link_to 'Back', admin_materials_path %>

app/views/admin/materials/index.html.erb
<h1><%= t('view.admin.materials') %></h1>
<p>素材一覧です</p>
<%= link_to new_admin_material_path do %>
  <button type="button" class="btn btn-primary">新規追加</button>
<% end %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">素材名</th>
      <th scope="col">説明</th>
      <th scope="col">カット可・不可</th>
      <th scope="col">刻印タイプ</th>
      <th scope="col">価格</th>
      <th scope="col">提供状況</th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <td><%= material.name %></td>
        <td><%= material.description %></td>
        <td><%= material.enable_cut ? '可' : '不可' %></td>
        <td><%= material.print_type_i18n %></td>
        <td><%= material.price %></td>
        <td><%= material.provide_status_i18n %></td>
        <td><%= link_to '編集', edit_admin_material_path(material) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/materials/new.html.erb
<h1>New Material</h1>

<%= render partial: 'form', locals: { material: @material, path_to_submit: admin_materials_path } %>

<%= link_to 'Back', admin_materials_path %>

app/views/admin/materials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content type:</strong>
  <%= @material.content_type %>
</p>

<p>
  <strong>Content value:</strong>
  <%= @material.content_value %>
</p>

<p>
  <strong>Status:</strong>
  <%= @material.status %>
</p>

<p>
  <strong>Internal comment:</strong>
  <%= @material.internal_comment %>
</p>

<p>
  <strong>External comment:</strong>
  <%= @material.external_comment %>
</p>

<p>
  <strong>Created user:</strong>
  <%= @material.created_user_id %>
</p>

<p>
  <strong>Updated user:</strong>
  <%= @material.updated_user_id %>
</p>

<p>
  <strong>Active:</strong>
  <%= @material.active %>
</p>

<%= link_to 'Edit', edit_material_path(@material) %> |
<%= link_to 'Back', materials_path %>