config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders
    resources :materials
  end

  resources :products
  get '/my_products', to: 'products#my_index'
  get '/my_products/:id', to: 'products#my_show'
  get 'top/index'

  resources :designs
  get '/my_designs', to: 'designs#my_index'

  resources :orders do
    collection do
      post :confirm
    end
  end
  get 'users/new'
  resources :users

  get 'password_resets/new'
  get 'password_resets/edit'

  root 'top#index'

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :account_activations, only: [:edit]

#  get 'static_pages/help'
#  get 'static_pages/about'
#  get 'static_pages/contact'

  #root 'application#hello'

  get 'login/index'
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/design.rb
# == Schema Information
#
# Table name: designs
#
#  id                       :integer          not null, primary key
#  user_id                  :integer          not null
#  name                     :string(255)      not null
#  enable_cut               :boolean          default(FALSE), not null
#  print_type               :integer          not null
#  design_original_filename :string(255)      not null
#  design_file              :string(255)      not null
#  active                   :boolean          default(FALSE), not null
#  created_user_id          :integer
#  updated_user_id          :integer
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#

class Design < ApplicationRecord

  # = Module & Configure
  mount_uploader :design_file, DesignFileUploader

  # = Association
  belongs_to :order, optional: true
  has_many :product


  # = Validation
  # validates :title, presence: true, length: { maximum: 120 }
  # validates :comment, length: { maximum: 500 }
  # validate do
  # end

  # = Callback
  # before_validation do
  # end

  before_save do
    self.design_original_filename ||= design_file.file.original_filename
  end

  # = Instance method
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  before_action :set_design, only: [:show, :edit, :update, :destroy]

  # GET /designs
  # GET /designs.json
  def index
    @designs = Design.all
  end

  # GET /designs/1
  # GET /designs/1.json
  def show
  end

  # GET /designs/new
  def new
    @design = Design.new
  end

  # GET /designs/1/edit
  def edit
  end

  # POST /designs
  # POST /designs.json
  def create
    @design = Design.new(design_params)

    respond_to do |format|
      if @design.save
        format.html { redirect_to @design, notice: 'Design was successfully created.' }
        format.json { render :show, status: :created, location: @design }
      else
        format.html { render :new }
        format.json { render json: @design.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /designs/1
  # PATCH/PUT /designs/1.json
  def update
    respond_to do |format|
      if @design.update(design_params)
        format.html { redirect_to @design, notice: 'Design was successfully updated.' }
        format.json { render :show, status: :ok, location: @design }
      else
        format.html { render :edit }
        format.json { render json: @design.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /my_designs
  # GET /my_designs.json
  def my_index
    @designs = Design.where(user_id: current_user.id)
    render 'my_index'
  end

  # GET /my_designs/1
  # GET /my_designs/1.json
  def my_show
    @design = Design.find(params[:id])
    render 'my_show'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_design
      @design = Design.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def design_params
      params.fetch(:design, {})
    end
end

app/helpers/designs_helper.rb
module DesignsHelper
end

app/views/designs/_form.html.erb
<%= form_for(design) do |f| %>
  <% if design.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(design.errors.count, "error") %> prohibited this design from being saved:</h2>

      <ul>
      <% design.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/designs/edit.html.erb
<h1>Editing Design</h1>

<%= render 'form', design: @design %>

<%= link_to 'Show', @design %> |
<%= link_to 'Back', designs_path %>

app/views/designs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Designs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @designs.each do |design| %>
      <tr>
        <td><%= link_to 'Show', design %></td>
        <td><%= link_to 'Edit', edit_design_path(design) %></td>
        <td><%= link_to 'Destroy', design, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Design', new_design_path %>

app/views/designs/my_index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('view.my_designs') %></h1>

<div class="row" style="display: -webkit-flex; display: flex; flex-wrap: wrap;" >
  <% @designs.each do |design| %>
    <div class="col col-sm-3 col-xs-6 ">
      <div class="panel panel-default">
        <div class="panel-body text-center">
          <!--<%= link_to image_tag(design.design_file.thumb, :border => '0', :size => '127x127', :style => 'object-fit: cover')%>-->
          <%= image_tag(design.design_file.thumb, :border => '0', :size => '127x127', :style => 'object-fit: cover')%>
        </div>
        <div class="panel-footer">
          <table class="table">
            <tbody>
              <tr><th><%= design.name %></th></tr>
              <tr><th>カット</th><th><%= design.enable_cut %></th></tr>
              <tr><th>刻印</th><th><%= design.print_type %></th></tr>
              <tr><th>作成日</th><th><%= design.created_at %></th></tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>

<%= link_to '新規追加', new_design_path %>

app/views/designs/my_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Design:</strong>
  <%= @product.design_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Product status:</strong>
  <%= @product.sale_status %>
</p>

<p>
  <strong>Active:</strong>
  <%= @product.active %>
</p>

<p>
  <strong>Created user:</strong>
  <%= @product.created_user_id %>
</p>

<p>
  <strong>Updated user:</strong>
  <%= @product.updated_user_id %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', my_products_path %>

app/views/designs/new.html.erb
<h1>New Design</h1>

<%= render 'form', design: @design %>

<%= link_to 'Back', designs_path %>

app/views/designs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_design_path(@design) %> |
<%= link_to 'Back', designs_path %>