config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders
    resources :materials
  end

  resources :products
  get '/my_products', to: 'products#my_index'
  get '/my_products/:id', to: 'products#my_show'
  get 'top/index'

  resources :designs
  get '/my_designs', to: 'designs#my_index'

  resources :orders do
    collection do
      post :confirm
    end
  end
  get 'users/new'
  resources :users

  get 'password_resets/new'
  get 'password_resets/edit'

  root 'top#index'

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :account_activations, only: [:edit]

#  get 'static_pages/help'
#  get 'static_pages/about'
#  get 'static_pages/contact'

  #root 'application#hello'

  get 'login/index'
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                      :integer          not null, primary key
#  design_id               :integer
#  material_id             :integer
#  name                    :string(255)
#  description             :text(65535)
#  image_original_filename :string(255)
#  image                   :string(255)
#  url                     :string(255)
#  price                   :integer
#  sale_status             :integer
#  active                  :boolean
#  created_user_id         :integer
#  updated_user_id         :integer
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#

class Product < ApplicationRecord

  # = Module & Configure
  enum sale_status: {
    private_sale: 0,
    public_sale: 10,
    sale_stopped: 20
  }

  # = Association
  belongs_to :design
  belongs_to :material
  has_many :order

  # = Callback
  before_validation do
    self.sale_status ||= :private_sale
    self.description ||= ''
    self.price ||= calculate_price
    self.active ||= true
  end

  # = Instance method

  def calculate_price
    # TODO:スタブとして固定値
    1000
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /my_products
  # GET /my_products.json
  def my_index
    @products = Product.joins(:design).where(designs: {user_id: current_user.id})
    render 'my_index'
  end

  # GET /my_products/1
  # GET /my_products/1.json
  def my_show
    @product = Product.find(params[:id])
    render 'my_show'
  end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:design_id, :name, :description, :price, :sale_status, :active, :created_user_id, :updated_user_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :design_id %>
    <%= f.number_field :design_id %>
  </div>

  <div class="field">
    <%= f.label :material_id %>
    <%= f.number_field :material_id %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :sale_status %>
    <%= f.number_field :sale_status %>
  </div>

  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>

  <div class="field">
    <%= f.label :created_user_id %>
    <%= f.text_field :created_user_id %>
  </div>

  <div class="field">
    <%= f.label :updated_user_id %>
    <%= f.number_field :updated_user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('view.products') %></h1>

<div class="row" style="display: -webkit-flex; display: flex; flex-wrap: wrap;" >
  <% @products.each do |product| %>
    <div class="col col-sm-3 col-xs-6 ">
      <div class="panel panel-default">
        <div class="panel-body text-center">
          <%= link_to image_tag(product.design.design_file.thumb, :border => '0', :size => '127x127', :style => 'object-fit: cover'), product %>
        </div>
          <table class="table" border="0">
            <tbody>
              <tr><th><%= product.name %></th><th></th></tr>
              <tr><th>価格</th><th>￥<%= product.price %></th></tr>
            </tbody>
          </table>
      </div>
    </div>
  <% end %>
</div>

<br>

<%= link_to '新規追加', new_product_path %>

app/views/products/my_index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('view.my_products') %></h1>

<div class="row" style="display: -webkit-flex; display: flex; flex-wrap: wrap;" >
  <% @products.each do |product| %>
    <div class="col col-sm-3 col-xs-6 ">
      <div class="panel panel-default">
        <div class="panel-body text-center">
          <%= link_to image_tag(product.design.design_file.thumb, :border => '0', :size => '127x127', :style => 'object-fit: cover'), "/my_products/" + product.id.to_s %>
        </div>
        <div class="panel-footer">
          <p>
            <%= product.description %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>

<%= link_to '新規追加', new_product_path %>

app/views/products/my_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Design:</strong>
  <%= @product.design_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Product status:</strong>
  <%= @product.sale_status %>
</p>

<p>
  <strong>Active:</strong>
  <%= @product.active %>
</p>

<p>
  <strong>Created user:</strong>
  <%= @product.created_user_id %>
</p>

<p>
  <strong>Updated user:</strong>
  <%= @product.updated_user_id %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', my_products_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Design:</strong>
  <%= @product.design_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Product status:</strong>
  <%= @product.sale_status %>
</p>

<%= link_to 'Back', products_path %>