config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders
    resources :materials
  end

  resources :products
  get '/my_products', to: 'products#my_index'
  get '/my_products/:id', to: 'products#my_show'
  get 'top/index'

  resources :designs
  get '/my_designs', to: 'designs#my_index'

  resources :orders do
    collection do
      post :confirm
    end
  end
  get 'users/new'
  resources :users

  get 'password_resets/new'
  get 'password_resets/edit'

  root 'top#index'

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :account_activations, only: [:edit]

#  get 'static_pages/help'
#  get 'static_pages/about'
#  get 'static_pages/contact'

  #root 'application#hello'

  get 'login/index'
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "KOBANZAME", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "製品", products_path %></li>
        <li><%= link_to "発注", new_order_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "設計", my_designs_path %></li>
              <li><%= link_to "製品", my_products_path %></li>
              <li><%= link_to "発注一覧", orders_path %></li>
              <li><%= link_to "プロフィール", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
          <% if current_user.admin? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                管理メニュー <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "ユーザー", users_path %></li>
                <li><%= link_to "素材", admin_materials_path %></li>
                <li><%= link_to "製品", products_path %></li>
                <li><%= link_to "注文管理", admin_orders_path %></li>
              </ul>
            </li>
          <% end %>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
        <li><%= link_to "ヘルプ", help_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<!--    <title>Arsr</title> -->
    <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>